/*
 * Sorting Tuples in Go
 *
 * API that allows users to signup/login to the server, giving them the ability to create input files of type csv, and sort the column data in them based on a certain column.
 *
 * API version: 0.1.0
 * Contact: mannaabaddour29699@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"UsersFoldersFilesFileDelete",
		strings.ToUpper("Delete"),
		"/users/folders/files/file",
		UsersFoldersFilesFileDelete,
	},

	Route{
		"UsersFoldersFilesFileGet",
		strings.ToUpper("Get"),
		"/users/folders/files/file",
		UsersFoldersFilesFileGet,
	},

	Route{
		"UsersFoldersFilesFilePost",
		strings.ToUpper("Post"),
		"/users/folders/files/file",
		UsersFoldersFilesFilePost,
	},

	Route{
		"UsersFoldersFilesFilePut",
		strings.ToUpper("Put"),
		"/users/folders/files/file",
		UsersFoldersFilesFilePut,
	},

	Route{
		"UsersFoldersFilesGet",
		strings.ToUpper("Get"),
		"/users/folders/files",
		UsersFoldersFilesGet,
	},

	Route{
		"UsersFoldersGet",
		strings.ToUpper("Get"),
		"/users/folders",
		UsersFoldersGet,
	},

	Route{
		"UsersFoldersPost",
		strings.ToUpper("Post"),
		"/users/folders",
		UsersFoldersPost,
	},

	Route{
		"UsersLoginPost",
		strings.ToUpper("Post"),
		"/users/login",
		UsersLoginPost,
	},

	Route{
		"UsersSettingsDelete",
		strings.ToUpper("Delete"),
		"/users/settings",
		UsersSettingsDelete,
	},

	Route{
		"UsersSettingsGet",
		strings.ToUpper("Get"),
		"/users/settings",
		UsersSettingsGet,
	},

	Route{
		"UsersSettingsPut",
		strings.ToUpper("Put"),
		"/users/settings",
		UsersSettingsPut,
	},

	Route{
		"UsersSignupPost",
		strings.ToUpper("Post"),
		"/users/signup",
		UsersSignupPost,
	},
}
